### ISSUE TITLE
How about "Digitally Imported" support?

### ISSUE THREAD

**Issue by DanyGee** [tjhrulz/WebNowPlaying#28]
Hi,
did you thought about adding support for [www.di.fm](url)? 🎧 
Don't know if its popular enough though 🤔 
Regardless of the decision, THANK YOU FOR YOUR PLUGIN! 🙏

**Comment by tjhrulz** [comment]
I mean I have no issue with adding support and really never have issue with adding support for a website as long as it will not be a giant pain (aka the website has very good counter measures to prevent me from doing so) to implement.

However my time is a little limited right now so if anyone wants to implement it themselves feel free to. Otherwise I will get to it when I can.

**Comment by goldenpipes** [comment]
+1000 !

**Comment by DanyGee** [comment]
Hello,
can we expect any update on this? Is anyone skilled enough to implement it?

**Comment by klezgt** [comment]
Hi, tjhrulz

Thanks a lot for your plugin, 
I just came across with the same question as a DanyGee
VK.com support in your plugin would be so much appreciated!

thanks in advance.
