### ISSUE TITLE
Bandcamp Support

### ISSUE THREAD

**Issue by Celysus** [tjhrulz/WebNowPlaying#36]
Would it be possible to include support for Bandcamp? 
Thank you for making this extension!

**Comment by tjhrulz** [comment]
Bandcamp support unfortunately is easier said than done due to how each site is a little different, however learning this was what caused my to create generic support that will get you most of the info you are looking for. You can enable this by going in the extension options (Usually just right click the extension), you can either set a whitelist of sites it works on, or a blacklist of sites for it to not work on.
