### ISSUE TITLE
Name of album Youtube Music

### ISSUE THREAD

**Issue by copystring** [tjhrulz/WebNowPlaying#39]
The name of the album on Youtube Music is a circle/dot instead of the actual name.

![image](https://user-images.githubusercontent.com/1298861/73128138-2b902780-3fcb-11ea-9dd3-1e2bd4422a96.png)

**Comment by copystring** [comment]
In YoutubeMusic.js line 49
`return document.getElementsByClassName("byline ytmusic-player-bar")[0].children[1].innerText;`
is now 
`return document.getElementsByClassName("byline ytmusic-player-bar")[0].children[2].innerText;`

then it works just fine again.

**Comment by xXNicksonXx** [comment]
Made a Pull Request

**Comment by AbleOne** [comment]
@tjhrulz this issue still relevant, please merge @xXNicksonXx 's [PR](https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/pull/46) 💪👍 to the `master` as well as to the Chrome Web Store 🙏🙏😉

**Comment by tjhrulz** [comment]
I really hate that no one makes a good GitHub app that actually gives me notifications, at least it seems the official one is getting somewhat better because it at least gave me one about this. I know I say this all the time and then I end up busy and it doesn't happen but I will look into this and this will be handled this week.

Cheers
Tj
