### ISSUE TITLE
Support For Web-based Desktop Apps? 

### ISSUE THREAD

**Issue by JordansplaceYT** [tjhrulz/WebNowPlaying#49]
Is it possible to make tidal work with rainmeter by chance ? - im aware its possible with the web-page version but im curious about the actual client since its more practical.  - thanks for your time

**Comment by tjhrulz** [comment]
It may be possible using script injection a la https://github.com/khanhas/spicetify-cli 

But this would be quite a bit of reverse engineering and work. Tidal is a service I personally use, and since position and volume setting do not work right but I could make work in the desktop app, this would be something I would like to see because of that. So I may eventually pester khanhas and figure out how to do it some day but I just know how difficult it would be. I would say just stick to using the web app and use chrome's app shortcuts to give it a more native feel and we can wish that someday that will change.

Also if anybody else wants to inject the scripts into tidal desktop feel free.

**Comment by tjhrulz** [comment]
So I had a few days recently to sit and play with this and I also looked at a few other web based desktop music players.

I pretty quickly got Qobuz up and running due to the fact that their desktop app is just completely unpacked, adding for it to load my scripts inside one of their scripts work perfect and shows that their desktop app and web app have the exact same layout and now changes are needed. All I need now is a nice way to deploy it so it is easy to install.

As for my still streaming service of choice Tidal (Although recently Qobuz and the soon coming Spotify HiFi may tempt me), I have tried to get my scripts to load but either I have not gotten them working or their desktop app has a different layout than their web app. I will need to sit with the plugin in debugging and the chrome dev tools see what I can gleam from this.

Amazon Music's desktop player is not a traditional web app (Who knew)

Deezer likely is a web app but since it is only available through the Microsoft Store so I will have to figure out how I can change that one but at least if other apps are any indication it is likely possible.

**Comment by ProgrammerCordelia** [comment]
Ah, maybe you can also experiment with the YouTube Music  Desktop App, they've got an API too.

**Comment by tjhrulz** [comment]
> Ah, maybe you can also experiment with the YouTube Music  Desktop App, they've got an API too. 

Which YouTube music desktop app? There are a lot of them the community has made.

**Comment by keifufu** [comment]
Other than Qobuz and Spotify, most desktop apps don't seem to be easily modifiable. Spotify already has WebNowPlaying support via [Spicetify](https://github.com/spicetify/spicetify-cli) and nobody seems to be interested in Qobuz support.
