### ISSUE TITLE
[Feature request] Meterstyle Bar for progress or time

### ISSUE THREAD

**Issue by MjolnirMouse** [tjhrulz/WebNowPlaying#51]
I was hoping we could get a way to display as a moving bar the progress thru the song. Or if its already possible how would it be done.

Thank you in advanve

**Comment by tjhrulz** [comment]
This is easily doable with this plugin using the progress type since that would return a value between 0-100 of how far into a song you are. 

Given making a progress bar using this is something pretty basic Rainmeter program if this is something you do not know how to do that I recommend going through the basic Rainmeter tutorials https://docs.rainmeter.net/manual-beta/getting-started/basic-tutorials/ specifically looking at the bar meter as that is what is intended to be used to display something like a progress bar. As for the using the plugin itself for that the example skin included in the installer for the plugin goes through using every PlayerType and bang that exists for this plugin. In your case though to make it easy I have copied the relevant code from the example for making a measure that returns the current percent of the way through the song.

```ini
[MeasureProgress]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=Progress
```
