### ISSUE TITLE
[Request] Make websocket traffic stateless

### ISSUE THREAD

**Issue by Kodikuu** [tjhrulz/WebNowPlaying#52]
1. Send full report to websocket in JSON format
eg;
'{"title": "blah", "artist": "bleh", "duration": 420, "position": 69, "state": 1, "coverurl": "someURL", "player": "spotiwhatever"}'

2. Only send when position or state changes (including position=0)

This should reduce the complexity of the receiving plugin, and prevent issues like the title not changing when switching pausing one source and unpausing another.

**Comment by tjhrulz** [comment]
Surprised you did not private message me about this.

I thought about using json but preferred the simplicity of just sending what has changed to cut down on CPU cycles. This actually ended up working out because my preferred json parser for C# seems to no longer want to play nice with ilmerge on my dev machine.

Also the extension does check if what it is about to send is the same as the last info that it sent and if it is it does not send it to the plugin. This has actually exposed some issues with other apps that have added support for the webNowPlaying plugin, which reminds me now that my ilmerge is working again I should go fix that one random bug cause by bad reverse engineering. Thanks!
