### ISSUE TITLE
Rainmeter cannot receive data from browser extension

### ISSUE THREAD

**Issue by mertturunc** [tjhrulz/WebNowPlaying#66]
Hi,
I'm using Rainmeter 4.4.0.3447 beta (64-bit) on Windows 10 and browser extension is up to date. My problem is:

![image](https://user-images.githubusercontent.com/16109023/118372487-8b448480-b5ba-11eb-970f-8cf0aeed06e1.png) 
<img src="https://user-images.githubusercontent.com/16109023/118372498-91d2fc00-b5ba-11eb-88bb-6146d01393cd.png" alt="example skin" width="200"/>

I tried a couple of different Rainmeter versions and older versions of the browser extension. Checked firewall, used Chrome and Opera, opened Rainmeter as Admin, and tried hardware acceleration on both programs.

Have a good day!

**Comment by mertturunc** [comment]
also this: 
![image](https://user-images.githubusercontent.com/16109023/118373789-3eb07780-b5c1-11eb-8fda-a88035f7f539.png)

**Comment by tjhrulz** [comment]
That looks like it is connected and sending info correctly but the page is having errors. Given it is Spotify I am guessing that you have the new redesign for spotify that just came out.

I still do not have access to it since it is being slowly rolled out so if that is the case there is nothing I can do for the time being as no one has found a way for force the new version via web.

However I also see a different language in the connected string, is your language for spotify not set to English? Given what all is giving errors I don't think this is the case but it may be that the new Spotify support we not language agnostic enough.

Could you right click the Rainmeter icon is the taskbar go to manage and then in that window go to settings and enable Debug mode under logging. Once you do that relaunch Rainmeter and post be your new Log screen, also screenshot what Spotify looks like for you so I can see if that has changed.

The place by the way to post that info will be here: https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/issues/74 as that is the Extension this is relevant to and I already have an issue open there.
