### ISSUE TITLE
Enhancement: Move the cached image location

### ISSUE THREAD

**Issue by DarkCoder28** [tjhrulz/WebNowPlaying#73]
I have been using this program for a few days now, and I really like it... my one big problem is that I use Nextcloud to sync my documents folder to my personal cloud and it keeps having to reupload the cover image, slowing down my internet speeds and adding unnecessary load to my server. I already had this problem with Rainmeter itself, but was able to change it's library directory away from the documents folder.

It would be great if you either changed the image cache location to somewhere like the temp directory or made some form of configuration for where to store it. 
Just a suggestion, but I would greatly appreciate it.

**Comment by keifufu** [comment]
I do believe it only re-downloads the cover if the address changed, but I'm not sure. @tjhrulz

**Comment by tjhrulz** [comment]
Likely your issue was in part caused by a skin not setting the default location as a relative location, if that is the case then it is just a matter of updating whatever skin is using it to have a relative path.

However if no skin sets a download location the plugin does download it to ~/Documents/Rainmeter/WebNowPlaying/cover.png as this was standard for plugins to do at the time. Given that how Microsoft wants the document folder to be used these days I will consider changing it to download to the temp directory but I will need to make sure that it does not affect backwards compatibility.
