### ISSUE TITLE
Web Side Errors for repeat and shuffle with stations on Amazon Music

### ISSUE THREAD

**Issue by ceylon23** [tjhrulz/WebNowPlaying#8]
When listening to a "Station" on Amazon Prime there is no "Shuffle" or "Repeat" available. This makes Rainmeter throw both a "Web Side Error:Error updating shuffle for Amazon Music" error and a "Web Side Error:Error updating repeat for Amazon Music" error every 100ms. However, when listening to an album or other playlist where "Shuffle" and "Repeat" are available, these errors do not occur.

**Comment by ceylon23** [comment]
Sorry... After reviewing the Browser Extension I have found that this issue belongs to that project.

**Comment by tjhrulz** [comment]
Also for future reference dont worry about rereporting about it in the wrong place the two projects are pretty well tied together right now anyways and I am capable of cross referencing stuff anyways.

Fixed with https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/commit/85b3db5c0aba88171555e749b48068082350a27b
